App = App || {};
App.data = [{"id": "acme-pills",
          "name": "Acme earthquake pills",
          "img": "pills.jpg",
          "price": {"amount": 3999, "currency": "eur"},
          "description": "Why wait? Make your own earthquakes! Loads of fun.",
          "manufacturer": "Acme Inc",
          "reviews": [{"name": "Guybrush Threepwood",
                     "email": "guybrush@example.com",
                     "stars": 5,
                     "review": "Huge success!"},
                     {"name": "Mike Mediocre",
                     "email": "mike@example.com",
                     "stars": 3,
                     "review": "This is OK in good company."},
                    {"name": "Haggis McMutton",
                     "email": "ilovehaggis@example.com",
                     "stars": 1,
                     "review": "This stinks big time.."}]},
         
         {"id": "fine-leather-jackets",
          "name": "Fine leather jacket",
          "img": "leatherjacket.jpg",
          "manufacturer": "Threepwood Pirate Clothing Inc",
          "price": {"amount": 245, "currency": "pieces-of-eight"},
          "description": "I'm selling these fine leather jackets",
          "reviews": [{"name": "Guybrush Threepwood",
                     "email": "guybrush@example.com",
                     "stars": 5,
                     "review": "Totally makes me look like an actual pirate!"},
                    {"name": "Haggis McMutton",
                     "email": "ilovehaggis@example.com",
                     "stars": 1,
                     "review": "Doesn't work as expected."}]},
         
         {"id": "log",
          "name": "Log from Blammo!",
          "img": "log.jpg",
          "price": {"amount": 1495, "currency": "eur"},
          "description": "It's log, log, It's big, it's heavy, it's wood. It's log, log, it's better than bad, it's good.",
          "manufacturer": "Blammo Toy Company"},
         
         {"id": "q36",
          "name": "Illudium Q-36 explosive space modulator",
          "img": "q36.jpg",
          "price": {"amount": 20000, "currency": "space-bucks"},
          "description": "Planets obstructing your view of Venus? Destroy them with the new explosive space modulator!",
          "manufacturer": "Transgalactic Tools Ltd",
          "reviews": []}]